# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: bitbucket
generate:
  client: true
  models: true
output: api.go
output-options:
  overlay:
    path: overlay.yaml